app_jobboard/urls.py
from django.urls import path
from . import views
from .views_folder import company_views, company_reviews

app_name = "jobboard"
urlpatterns = [
    path("", views.index, name="index"),
    path("job/<uuid:id>/", views.getJob, name="job"),
    path("createJob/", views.createJob, name="createJob"),
    path("myJobs/", views.getUserJobs, name="getUserJobs"),
    path("company/", views.companies, name="companies"),
    path("editJob/<uuid:id>/", views.editJob, name="editJob"),
    path("deleteJob/<uuid:id>/", views.deleteJob, name="deleteJob"),
    path("deleteSearch/<int:id>/", views.deleteSearch, name="deleteSearch"),
    path("bookmark/<uuid:jobId>/", views.addJobToBookmark, name="addBookmark"),
    path(
        "remove_bookmark/<uuid:jobId>/",
        views.removeJobFromBookmark,
        name="removeBookmark",
    ),
    path("company/<uuid:id>/", company_views.company, name="company"),
    path("company/create", company_views.createCompany, name="createCompany"),
    path("company/edit/<uuid:id>/", company_views.editCompany, name="editCompany"),
    path("company/delete/<uuid:id>/", company_views.deleteCompany, name="deleteCompany"),
    path("companies/", company_views.userCompanies, name="userCompanies"),
    path(
        "company/<uuid:companyId>/createReview/",
        company_reviews.create_review,
        name="createCompanyReview",
    ),
    path("review/edit/<int:id>/", company_reviews.edit_review, name="editReview"),
    path("review/delete/<int:id>/", company_reviews.delete_review, name="deleteReview"),
]

# TODO: Organize URLS into separate files.
# TODO: Change bookmark, and remove bookmark view to only retun json response

jobboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("app_jobboard.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path('auth/', include("authentication.urls")),
    path('admin/', admin.site.urls)
]

jobboard/authentication/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from .forms import RegisterForm
from .models import CustomUser
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required


def index(request):
    # To make sure the user is not logged in already
    if request.user.is_authenticated:
        return redirect("jobboard:home")
    # TODO: Have the index page manage both the login and register template using JavaScript, so both loginUser, and registerUser view would only allow POST methods.
    return render(request, "authentication/login.html")


@require_http_methods(["POST"])
def loginUser(request):
    email = request.POST.get("email")
    password = request.POST.get("password")

    # Checks if an email address has been provided.
    if not email:
        messages.error(request, "Please enter an email address")
        return redirect("/auth")
    # Checks if a password has been provided.
    if not password:
        messages.error(request, "Please enter a password.")
        return redirect("/auth")

    # Tries to authenticate user, and if successful, it logs in the user.
    User = authenticate(request=request, email=email.lower(), password=password)
    if User is not None:
        login(request, User)
        return redirect("jobboard:home")
    else:
        messages.error(request, "Invalid username or password has been provided")
        return redirect("/auth")


def registerUser(request):
    if request.method == "POST":
        email = request.POST.get("email")
        first_name = request.POST.get("first_name")
        middle_name = request.POST.get("middle_name")
        last_name = request.POST.get("last_name")
        role = request.POST.get("role")
        password = request.POST.get("password")

        # TODO: Better validation for passwords, and for roles.

        if not first_name or not last_name:
            messages.error(request, "You must provide a first name, and a last name.")
            return redirect("register")
        if not email or not password:
            messages.error(
                request, "You must provide a password, and an email address."
            )
            return redirect("register")
        if not role:
            messages.error(request, "You must provide a role.")
            return redirect("register")

        try:
            User = CustomUser.objects.create(
                email=email.lower(),
                password=password,
                first_name=first_name,
                last_name=last_name,
                middle_name=middle_name,
                role=role,
            )
            User.save()
            login(request=request, user=User)
            return redirect("home")
        except:
            messages.error(request, "Error trying to create your account.")
            return redirect("register")

    return render(request, "authentication/register.html")


@login_required(login_url="/auth")
def logoutUser(request):
    logout(request)
    return redirect("index")

templates/jobboard/companies.html
{% extends "layout.html" %} {% block title %} - Register {% endblock %} 

{% block searchComponent %}
		<div class="flex flex-col shadow-md pb-4 px-4">
			<form
				action="{% url 'jobboard:companies' %}"
				class="flex flex-row gap-4 items-center w-full justify-center px-40 mt-12">
				{% if q %}
				<input
					type="text"
					name="q"
					id="q"
					placeholder="{{ q }}"
					class="py-3 rounded-md font-light w-full" />
				{% else %}
				<input
					type="text"
					name="q"
					id="q"
					placeholder="Company name or keywords"
					class="py-3 rounded-md font-light w-full" />
				{% endif %}
				<button
					type="submit"
					class="w-fit h-fit px-4 py-2 bg-blue-500 text-white">
					Search
				</button>
			</form>
			{% if q %}
				<a href="?q=" class="font-light text-gray-500 text-sm underline cursor-pointer self-end">Clear search</a>
			{% endif %}
		</div>
	{% endblock %}


{% block content %}
<h1 class="w-full text-center text-4xl mt-8 mb-4 text-blue-500 font-bold">Company List</h1>
<p class="font-light text-gray-500 text-sm self-end">Currently displaying {{companies.count}} company</p>
<div class="mt-4 flex flex-col gap-2">
    {% for company in companies %}
	<div class="border w-full px-2 py-2 flex flex-row justify-between items-center">
		<a href="{% url 'jobboard:company' company.id %}">{{ company.name }}</a>
		{% if company.category %}
			<a class="bg-slate-200 text-slate-700 w-fit text-sm h-fit py-1 rounded-md px-3">
				{{ company.category.name }}
			</a>
		{% endif %}
	</div>
	{% empty %}
	{% if q %}
		<div class="w-full flex flex-col justify-start text-gray-400">
			<p class="text-2xl font-light">
				The search <strong>"{{ q }}"</strong> did not match any companies.
			</p>
			<h4 class="font-medium text-lg mt-4 text-gray-500">
				Search suggestions:
			</h4>
			<ul class="list-disc list-inside font-light">
				<li>Try more general keywords</li>
				<li>Check your spelling</li>
				<li>Replace abbreviations with the entire word</li>
			</ul>
		</div>
	{% else %}
		<p class="text-2xl font-light">
			There are currently no companies available.
		</p>
	{% endif %}
    {% endfor %}
</div>

{% endblock %}

templates/jobboard/company.html
{% extends "layout.html" %} 
{% load static %} 

{% load crispy_forms_tags %} {% block title %}
 - Register 
{% endblock %} 

{% block searchComponent %} 
{% endblock %}

{% block content %}
<div class="mt-12 px-2 md:px-0">
	<div class="flex flex-row justify-between items-center">
		<div>
			<h1 class="text-4xl font-semibold underline">{{ company.name }}</h1>
			{% if company.category %}
			<p>{{ company.category }}</p>
			{% endif %}
		</div>
		{% if company.isLookingForEmployees %}
		<p class="text-red-400 text-xs text-right">
			Currently looking for employees
		</p>
		{% endif %}
	</div>

	<p class="mt-3 font-light text-gray-500">{{ company.description }}</p>

	<section>
		<a
			href="#jobs"
			class="flex flex-row gap-3 mt-12 items-center w-full bg-blue-500 text-white py-1 px-3">
			<span class="font-light text-2xl">#</span>
			<h4 class="font-medium text-xl">JOBS</h4>
		</a>
		<div class="mt-4 px-4 flex flex-col gap-3">
			{% for job in jobs %}
			<div
				class="font-light border px-4 py-2 w-full flex flex-row justify-between items-center gap-2 flex-wrap">
				<a href="{% url 'jobboard:job' job.id %}">{{ job.name }}</a>

				<div class="flex flex-row gap-2">
					<a
						href="/?q={{ job.location }}"
						class="bg-slate-200 text-slate-700 w-fit px-3 h-fit"
						>{{ job.location }}</a
					>
					<a
						href="/?q={{ job.employment_type }}"
						class="bg-slate-200 text-slate-700 w-fit px-3 h-fit">
						{{ job.employment_type }}
					</a>
				</div>
			</div>
			{% endfor %}
		</div>
	</section>

	<section class="flex flex-col mt-9">
		<header
			class="flex flex-row justify-between gap-2 bg-blue-500 text-white py-1 px-3 items-center">
			<a href="#reviews" class="flex flex-row gap-3 items-center w-full">
				<span class="font-light text-2xl">#</span>
				<h4 class="font-medium text-xl">REVIEWS</h4>
			</a>
			{% if request.user.is_authenticated %}
			<div>
				<p
					id="toggle-review"
					data-status="false"
					class="w-max cursor-pointer">
					Add Review
				</p>
			</div>
			{% endif %}
		</header>

		{% if request.user.is_authenticated %}
		<div id="reviewForm" class="px-2 py-1">
			<form
				method="POST"
				action="{% url 'jobboard:createCompanyReview' companyId=company.id %}">
				{% csrf_token %}
				<p id="error" class="text-red-500 font-light text-sm"></p>
				<legend
					class="text-lg text-gray-500 underline underline-offset-1">
					Add a new review
				</legend>
				<textarea
					name="review"
					cols="20"
					rows="5"
					class="w-full"
					id="add-review"
					placeholder="How was your work experience with {{ company.name }}?"></textarea>
				<button
					type="submit"
					id="submit-review-btn"
					class="bg-blue-500 px-6 w-full py-1 text-white">
					Create Review
				</button>
			</form>
		</div>
		{% endif %}

		<div class="flex flex-col gap-4 px-2 my-4">
			{% for review in reviews %}
			<div id="{{ review.id }}" class="border px-2 py-1">
				<div class="flex flex-row justify-between gap-4">
					<h4 class="">
						<a
							class="underline"
							href="#"
							target="_blank"
							rel="noopener noreferrer"
							>{{ review.reviewer.first_name }}</a
						>
						Says,
					</h4>
					{% if review.reviewer == request.user %}
					<div
						class="flex flex-row gap-4 font-light text-xs justify-end">
						<button
							class="edit-review-btn"
							data-id="{{ review.id }}"
							href="">
							Edit
						</button>
						<button><a href="{% url 'jobboard:deleteReview' id=review.id %}"
							>Delete</a
						></button>
					</div>
					{% endif %}
				</div>
				<p class="font-light">{{ review.review }}</p>
			</div>
			{% endfor %}
		</div>
	</section>
</div>
{% endblock %} {% block js %}
<script src="{% static 'js/reviewForm.js' %}"></script>
<script src="{% static 'js/editReview.js' %}"></script>
{% endblock %}

templates/jobboard/createJob.html
{% extends "layout.html" %} {% block title %} - Register {% endblock %} 
{%load crispy_forms_tags %} 

{% block aboveContent %}
<div class="mt-4">
	<h1 class="w-full bg-blue-500 text-white px-4 py-2 font-light text-2xl">Create a new job posting</h1>
</div>
{% endblock %}

{% block content %}
<div>
    <form action="./" method="POST" class="my-4">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="bg-red-400 text-white p-4">Submit</button>
    </form>
</div>

{% endblock %}

templates/jobboard/editJob.html
{% extends "layout.html" %} {% block title %} - Register {% endblock %} 

{% block content %}
<div>
	<nav>
		{% if request.user.is_authenticated %}
		<p>
			Logged in as {{ request.user.first_name }} {{ request.user.last_name }}
		</p>
		<a href="/auth/logout">Logout</a>
		{% else %}
		<a href="/auth">Login</a>
		{% endif %}
	</nav>

    <form action="./{{ id }}" method="POST" class="my-4">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit" class="bg-red-400 text-white p-4">Submit</button>
    </form>
</div>

{% endblock %}

templates/jobboard/job.html
{% extends "layout.html" %} {% block title %} - Register {% endblock %} 


{% block content %}
<div class="mb-4">
	<div class="flex flex-row justify-between gap-8 items-center">
		<div>	
			<h3 class="font-semibold text-2xl">{{ job.name }}</h3>
			{% if job.company %}
				<a class="underline text-blue-500 font-light" href="{% url 'jobboard:company' job.company.id %}">{{ job.company.name }}</a>
			{% endif %}
			<p>{{ job.location }}</p> 
		</div>
		<a href="{{ job.apply_link}}" target="_blank" class="bg-blue-500 hover:bg-blue-400 border-blue-700 rounded-sm duration-300 px-5 py-2 w-fit h-fit text-white">Apply Here</a>
	</div>

	<div class="mt-4">
		<h4 class="font-light text-xl">Employment Type</h4>
		<a href="/?q={{ job.employment_type }}" class="text-xs mx-4 bg-slate-200 text-slate-700 w-fit px-3">
			{{ job.employment_type }}
		</a>
	</div>

	<div class="flex flex-col gap-2 mt-4">
		<h4 class="font-normal text-xl">Job Details</h4>
			
        <p class="font-light px-4">{{ job.description }}</p>

		{% if job.salary %}
			<h4 class="font-normal text-xl">Salary</h4>
			<p class="font-light mx-4 text-normal bg-slate-200 text-slate-700 w-fit px-3">{{ job.salary }} {{ job.currency }}</p>
		{% endif %}

	</div>

	<div class="my-4">
		<h4 class="font-normal text-xl">Skills Required</h4>
		<p class="px-4 font-light">{{ job.skills_required }}</p>
	</div>

</div>
{% endblock %}

templates/jobboard/manageCompanies.html
{% extends "layout.html" %} {% block title %} - Register {% endblock %} 

{% block searchComponent %}
<div class="flex flex-col shadow-md pb-4 px-4">
    <form
        action="{% url 'jobboard:userCompanies' %}"
        class="flex flex-row gap-4 items-center w-full justify-center px-40 mt-12">
        {% if q %}
        <input
            type="text"
            name="q"
            id="q"
            placeholder="{{ q }}"
            class="py-3 rounded-md font-light w-full" />
        {% else %}
        <input
            type="text"
            name="q"
            id="q"
            placeholder="Company name or keywords"
            class="py-3 rounded-md font-light w-full" />
        {% endif %}
        <button
            type="submit"
            class="w-fit h-fit px-4 py-2 bg-blue-500 text-white">
            Search
        </button>
    </form>
    {% if q %}
        <a href="?q=" class="font-light text-gray-500 text-sm underline cursor-pointer self-end">Clear search</a>
    {% endif %}
</div>
{% endblock %}

{% block content %}
<div class="mb-4">
    <h1 class="w-full text-center text-4xl mt-8 mb-4 text-blue-500 font-bold">My Companies</h1>
    <p class="font-light text-gray-500 text-sm self-end">Currently displaying {{companies.count}} company</p>
    <div class="flex flex-col gap-4 mt-4">
        {% for company in companies %}
        <div class="flex flex-row justify-between px-2 py-2 border hover:shadow-md duration-300">
            <div class="flex flex-row justify-between w-full">
                <div class="flex flex-row gap-2 items-center">
                    <a class="block text-lg" href="{% url 'jobboard:company' company.id %}">{{ company.name }}<a/>
                        <a href="" class="text-xs w-fit h-fit bg-slate-200 text-slate-700 px-3">
                            <!-- {{ job.employment_type }} -->
                        </a>
                </div>
                <div class="flex flex-row gap-3 items-center">
                    <a href="{% url 'jobboard:editCompany' company.id %}?next={{ request.path }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                          </svg>                      
                    </a>
                    <a href="{% url 'jobboard:deleteCompany' company.id %}?next={{ request.path }}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                          </svg>                      
                    </a>
                    
                </div>
                <!-- <a class="text-gray-400 text-sm">{{ job.company.name }}<a/> -->
            </div>

        </div>
        {% empty %}
            {% if q %}
                <div class="w-full flex flex-col justify-start text-gray-400">
                    <p class="text-2xl font-light">
                        The search <strong>"{{ q }}"</strong> did not match any companies.
                    </p>
                    <h4 class="font-medium text-lg mt-4 text-gray-500">
                        Search suggestions:
                    </h4>
                    <ul class="list-disc list-inside font-light">
                        <li>Try more general keywords</li>
                        <li>Check your spelling</li>
                        <li>Replace abbreviations with the entire word</li>
                    </ul>
                </div>
            {% else %}
                <p class="text-2xl font-light">
                    You currently have no companies.
                </p>
	{% endif %}

        {% endfor %}
    </div>
</div>
{% endblock %}

templates/jobboard/manageJobs.html
{% extends "layout.html" %} {% block title %} - Register {% endblock %} 

{% block searchComponent %}
    <div class="flex flex-col shadow-md pb-4 px-4">
        <form
            action="{% url 'jobboard:getUserJobs' %}"
            class="flex flex-row gap-4 items-center w-full justify-center px-40 mt-12">
            {% if q %}
            <input
                type="text"
                name="q"
                id="q"
                placeholder="{{ q }}"
                class="py-3 rounded-md font-light w-full" />
            {% else %}
            <input
                type="text"
                name="q"
                id="q"
                placeholder="Company name or keywords"
                class="py-3 rounded-md font-light w-full" />
            {% endif %}
            <button
                type="submit"
                class="w-fit h-fit px-4 py-2 bg-blue-500 text-white">
                Search
            </button>
        </form>
        {% if q %}
            <a href="?q=" class="font-light text-gray-500 text-sm underline cursor-pointer self-end">Clear search</a>
        {% endif %}
    </div>
{% endblock %}

{% block content %}
<div class="mb-4">
    <h1 class="w-full text-center text-4xl mt-8 mb-4 text-blue-500 font-bold">My Jobs</h1>
    <p class="font-light text-gray-500 text-sm self-end">Currently displaying {{jobs.count}} jobs</p>

    <div class="flex flex-col gap-4">
        {% for job in jobs %}
        <div class="flex flex-row justify-between px-2 py-2 border hover:shadow-md duration-300">
            <div>
                <div class="flex flex-row gap-2 items-center">
                    <a class="block text-lg" href="{% url 'jobboard:job' job.id %}">{{ job.name }}<a/>
                        <a href="/?q={{ job.employment_type }}" class="text-xs w-fit h-fit bg-slate-200 text-slate-700 px-3">
                            {{ job.employment_type }}
                        </a>
                </div>
                <a class="text-gray-400 text-sm">{{ job.company.name }}<a/>
            </div>

            <div class="flex flex-row gap-3 items-center">
                <a href="{% url 'jobboard:editJob' job.id %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                      </svg>                      
                </a>
                <a href="{% url 'jobboard:deleteJob' job.id %}?next={{ request.path }}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                      </svg>                      
                </a>
                
            </div>
        </div>
        {% empty %}
            {% if q %}
                <div class="w-full flex flex-col justify-start text-gray-400">
                    <p class="text-2xl font-light">
                        The search <strong>"{{ q }}"</strong> did not match any of your jobs.
                    </p>
                    <h4 class="font-medium text-lg mt-4 text-gray-500">
                        Search suggestions:
                    </h4>
                    <ul class="list-disc list-inside font-light">
                        <li>Try more general keywords</li>
                        <li>Check your spelling</li>
                        <li>Replace abbreviations with the entire word</li>
                    </ul>
                </div>
            {% else %}
                <p class="text-2xl font-light">
                    You currently have no jobs assigned to your account.
                </p>
            {% endif %}

        {% endfor %}
    </div>
</div>
{% endblock %}