app_jobboard/urls.py
from django.urls import path
from . import views
from .views_folder import company_views, company_reviews

app_name = "jobboard"
urlpatterns = [
    path("", views.index, name="index"),
    path("job/<uuid:id>/", views.getJob, name="job"),
    path("createJob/", views.createJob, name="createJob"),
    path("myJobs/", views.getUserJobs, name="getUserJobs"),
    path("company/", views.companies, name="companies"),
    path("editJob/<uuid:id>/", views.editJob, name="editJob"),
    path("deleteJob/<uuid:id>/", views.deleteJob, name="deleteJob"),
    path("deleteSearch/<int:id>/", views.deleteSearch, name="deleteSearch"),
    path("bookmark/<uuid:jobId>/", views.addJobToBookmark, name="addBookmark"),
    path(
        "remove_bookmark/<uuid:jobId>/",
        views.removeJobFromBookmark,
        name="removeBookmark",
    ),
    path("company/<uuid:id>/", company_views.company, name="company"),
    path("company/create", company_views.createCompany, name="createCompany"),
    path("company/edit/<uuid:id>/", company_views.editCompany, name="editCompany"),
    path("company/delete/<uuid:id>/", company_views.deleteCompany, name="deleteCompany"),
    path("companies/", company_views.userCompanies, name="userCompanies"),
    path(
        "company/<uuid:companyId>/createReview/",
        company_reviews.create_review,
        name="createCompanyReview",
    ),
    path("review/edit/<int:id>/", company_reviews.edit_review, name="editReview"),
    path("review/delete/<int:id>/", company_reviews.delete_review, name="deleteReview"),
]

# TODO: Organize URLS into separate files.
# TODO: Change bookmark, and remove bookmark view to only retun json response

jobboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("app_jobboard.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path('auth/', include("authentication.urls")),
    path('admin/', admin.site.urls)
]

templates/company/create.html
{% extends "layout.html" %} {% block title %} - Register {% endblock %} 
{%load crispy_forms_tags %} 

{% block aboveContent %}
<div class="mt-4">
	<h1 class="w-full bg-blue-500 text-white px-4 py-2 font-light text-2xl">Add a new company.</h1>
</div>
{% endblock %}

{% block content %}
<div>
    {% if mode == "edit" %}
        <form action="{% url 'jobboard:editCompany' company.id %}" method="POST" class="my-4">
    {% else %}
        <form action="{% url 'jobboard:createCompany' %}" method="POST" class="my-4">
    {% endif %}
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="bg-red-400 text-white p-4">Submit</button>
    </form>
</div>

{% endblock %}