app_jobboard/urls.py
from django.urls import path
from . import views
from .views_folder import company_views, company_reviews

app_name = "jobboard"
urlpatterns = [
    path("", views.index, name="index"),
    path("job/<uuid:id>/", views.getJob, name="job"),
    path("createJob/", views.createJob, name="createJob"),
    path("myJobs/", views.getUserJobs, name="getUserJobs"),
    path("company/", views.companies, name="companies"),
    path("editJob/<uuid:id>/", views.editJob, name="editJob"),
    path("deleteJob/<uuid:id>/", views.deleteJob, name="deleteJob"),
    path("deleteSearch/<int:id>/", views.deleteSearch, name="deleteSearch"),
    path("bookmark/<uuid:jobId>/", views.addJobToBookmark, name="addBookmark"),
    path(
        "remove_bookmark/<uuid:jobId>/",
        views.removeJobFromBookmark,
        name="removeBookmark",
    ),
    path("company/<uuid:id>/", company_views.company, name="company"),
    path("company/create", company_views.createCompany, name="createCompany"),
    path("company/edit/<uuid:id>/", company_views.editCompany, name="editCompany"),
    path("company/delete/<uuid:id>/", company_views.deleteCompany, name="deleteCompany"),
    path("companies/", company_views.userCompanies, name="userCompanies"),
    path(
        "company/<uuid:companyId>/createReview/",
        company_reviews.create_review,
        name="createCompanyReview",
    ),
    path("review/edit/<int:id>/", company_reviews.edit_review, name="editReview"),
    path("review/delete/<int:id>/", company_reviews.delete_review, name="deleteReview"),
]

# TODO: Organize URLS into separate files.
# TODO: Change bookmark, and remove bookmark view to only retun json response

authentication/urls.py
from django.urls import path
from . import views

app_name = "auth"
urlpatterns = [
    path("", views.index, name="index"),
    path("user/", views.user, name="user"),
    path("edituser/", views.editUser, name="editUser"),
    path("login/", views.loginUser, name="login"),
    path("register/", views.registerUser, name="register"),
    path("logout/", views.logoutUser, name="logout"),
]

jobboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("app_jobboard.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path('auth/', include("authentication.urls")),
    path('admin/', admin.site.urls)
]

templates/index.html
{% extends "layout.html" %} {% block title %} - Register {% endblock %} 

{% load static %} 
{% block js %}
	<script>
		const searchInput = document.getElementById("q");
		searchInput.addEventListener("change", (e) => {
			const urlParams = new URLSearchParams(window.location.search);
			urlParams.set("q", e.target.value);
			window.location.search = urlParams;
		});
	</script>
{% endblock %} 


{% block content %} 
{% if tab != "recent_searches" %} 
{% if q %}
<a href="?q=" class="font-light text-gray-500 text-sm underline cursor-pointer">Clear search</a>
{% endif %}
<div class="flex flex-row justify-center gap-4 pt-8 relative mb-4">
	<div class="flex flex-col gap-2 mb-4">
		{% for job in jobs %}
		<div class="justify-between border sm:max-w-[600px] max-w-[400px] px-4 py-3 rounded-sm hover:shadow-md duration-300 transition-all">
			<div class="flex flex-row justify-between">
				<a
					href="{% url 'jobboard:job' job.id %}"
					class="text-xl"
					>{{ job.name }}</a
				>
				{% if job.employer == request.user %}
				<svg
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					stroke-width="1.5"
					stroke="currentColor"
					class="w-6 h-6">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						d="M3.75 5.25h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5" />
				</svg>
				{% endif %}
			</div>
			<div class="flex flex-row gap-2 font-light text-slate-600">
				<p>{{ job.company_name }}</p>
				|
				<p class="font-normal">{{ job.location }}</p>
			</div>
			<div class="flex flex-row gap-4 px-2 text-sm mt-2">
				{% if job.salary %}
				<p
					class="bg-slate-100 text-slate-600 px-3 border border-slate-400 rounded-sm">
					${{ job.salary }} monthly
				</p>

				{% endif %}
				<a href="/?q={{ job.employment_type }}" class="bg-slate-200 text-slate-700 w-fit px-3">
					{{ job.employment_type }}
				</a>
			</div>
			<section
				aria-label="job summary"
				class="my-2 font-light text-gray-500">
				{{ job.summary }}
			</section>
			<footer aria-label="job footer" class="mt-2">
				<p class="font-light text-xs text-gray-600">
					Posted {{ job.created_at|timesince }} ago.
				</p>
			</footer>
		</div>
		{% empty %} {% if q %}
		<div class="w-full flex flex-col justify-start text-gray-400">
			<p class="text-2xl font-light">
				The search <strong>"{{ q }}"</strong> did not match any jobs.
			</p>
			<h4 class="font-medium text-lg mt-4 text-gray-500">
				Search suggestions:
			</h4>
			<ul class="list-disc list-inside font-light">
				<li>Try more general keywords</li>
				<li>Check your spelling</li>
				<li>Replace abbreviations with the entire word</li>
			</ul>
		</div>

		{% else %}
		<p>There are currently no jobs available.</p>
		{% endif %} {% endfor %}
	</div>

	{% else %}
	<!-- Recent Searches Tab -->
	<section class="text-black flex flex-col gap-2">
		<h3 class="font-medium text-xl">Here are your recent searches...</h3>
		{% for search in recent_searches %}
		<div
			class="flex flex-row py-2 px-4 border mx-12 w-full justify-between">
			<a href="?q={{ search.search }}&tab=" class="font-light"
				>{{ search.search }}</a
			>
			<a href="{% url 'jobboard:deleteSearch' search.id %}"><svg
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 20 20"
				fill="currentColor"
				class="w-5 h-5 cursor-pointer">
				<path
					fill-rule="evenodd"
					d="M8.75 1A2.75 2.75 0 006 3.75v.443c-.795.077-1.584.176-2.365.298a.75.75 0 10.23 1.482l.149-.022.841 10.518A2.75 2.75 0 007.596 19h4.807a2.75 2.75 0 002.742-2.53l.841-10.52.149.023a.75.75 0 00.23-1.482A41.03 41.03 0 0014 4.193V3.75A2.75 2.75 0 0011.25 1h-2.5zM10 4c.84 0 1.673.025 2.5.075V3.75c0-.69-.56-1.25-1.25-1.25h-2.5c-.69 0-1.25.56-1.25 1.25v.325C8.327 4.025 9.16 4 10 4zM8.58 7.72a.75.75 0 00-1.5.06l.3 7.5a.75.75 0 101.5-.06l-.3-7.5zm4.34.06a.75.75 0 10-1.5-.06l-.3 7.5a.75.75 0 101.5.06l.3-7.5z"
					clip-rule="evenodd" />
			</svg></a>
		</div>
		{% endfor %}
	</section>
	{% endif %} {% endblock %}

	<button class="bg-red-300 px-2 py-1">
		<a href="{% url 'jobboard:editJob' job.id %}">Edit</a>
	</button>
	<button class="bg-red-300 px-2 py-1">
		<a href="{% url 'jobboard:deleteJob' job.id %}">Delete</a>
	</button>
</div>

templates/layout.html
{% extends "base.html" %}

{% block mainContent %}
	{% include "nav_bar.html" %}

	{% block searchComponent %}
		<div class="flex flex-col gap-4">
			<form
				action="/"
				class="flex flex-row gap-4 items-center w-full justify-center px-40 mt-12">
				{% if q %}
				<input
					type="text"
					name="q"
					id="q"
					placeholder="{{ q }}"
					class="py-3 rounded-md font-light w-full" />
				{% else %}
				<input
					type="text"
					name="q"
					id="q"
					placeholder="Job title, company or keywords"
					class="py-3 rounded-md font-light w-full" />
				{% endif %}
				<button
					type="submit"
					class="w-fit h-fit px-4 py-2 bg-blue-500 text-white">
					Search
				</button>
			</form>
		
			<div class="flex flex-row gap-8 justify-center mt-2">
				{% if not user.is_authenticated %}
					<p class="text-xl font-medium cursor-default text-blue-500">Job Feed</>
				{% else %}
					{% if tab == "recent_searches"%}
					<a href="/?tab=" class="text-xl font-light">Job Feed</a>
					<a href="/?tab=recent_searches" class="font-medium text-xl text-blue-500"
						>Recent Searches</a
					>
					{% else%}
					<a href="/?tab=" class="font-medium text-xl text-blue-500">Job Feed</a>
					<a href="/?tab=recent_searches" class="font-light text-xl"
						>Recent Searches</a
					>
					{% endif %}
				{% endif %}
			</div>
		
			<hr />
		</div>
	{% endblock %}

	<div class="container mx-auto mt-4">
		{% if messages %}
			<ul class="messages">
				{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
		{% endif %}
		
		{% block content %}

		{% endblock %}
	</div>
{% endblock %}

templates/nav_bar.html
{% block content %}
<div>
	<nav
		class="w-full flex flex-row justify-between shadow-md px-4 py-3 items-center">
		<ul class="flex flex-row gap-5">
			<li>
				<a
					class="font-medium hover:text-blue-400 cursor-pointer duration-500 transition-colors"
					href="/"
					>Find jobs</a
				>
			</li>
			<li>
				<a
					href="{% url 'jobboard:companies' %}"
					class="font-medium hover:text-blue-400 cursor-pointer duration-500 transition-colors"
					>Companies</a
				>
			</li>
			{% if request.user.is_authenticated %}
			<li>
				<a
					href="{% url 'jobboard:getUserJobs' %}"
					class="font-medium hover:text-blue-400 cursor-pointer duration-500 transition-colors"
					>Manage Jobs</a
				>
			</li>
			<li>
				<a
					href="{% url 'jobboard:userCompanies' %}"
					="font-medium hover:text-blue-400 cursor-pointer duration-500 transition-colors"
					>Manage Companies</a
				>
			</li>
			{% endif %}
		</ul>
		<div class=" ">
			{% if request.user.is_authenticated %}

			<div class="flex flex-row gap-6">
				<div class="flex flex-row gap-2 items-center">
					<a href="{% url 'auth:user' %}"
						><svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 24 24"
							stroke-width="1.5"
							stroke="currentColor"
							class="w-8 cursor-pointer h-8">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" /></svg
					></a>
					<svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						viewBox="0 0 24 24"
						stroke-width="1.5"
						stroke="currentColor"
						class="w-8 cursor-pointer h-8">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
					</svg>
				</div>
				<a
					class="bg-blue-400 text-white px-4 py-1 w-fit h-fit rounded-sm shadow-md"
					href="{% url 'jobboard:createJob' %}"
					>Post a job</a
				>
			</div>
			{% else %}
			<a href="/auth">Login</a>
			{% endif %}
		</div>
	</nav>
</div>
{% endblock %}